# Generated by Django 4.2 on 2025-05-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название народа')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('history', models.TextField(default='История отсутствует', verbose_name='История')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='Регион')),
                ('language', models.CharField(blank=True, max_length=64, verbose_name='Язык')),
                ('religion', models.CharField(blank=True, max_length=64, verbose_name='Религия')),
                ('population', models.CharField(blank=True, max_length=64, verbose_name='Численность')),
            ],
        ),
        migrations.CreateModel(
            name='NationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='nation_images/')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nation.nation')),
            ],
        ),
    ]
