# Generated by Django 4.2 on 2025-05-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='region',
        ),
        migrations.AddField(
            model_name='nation',
            name='culture',
            field=models.TextField(blank=True, verbose_name='Культура'),
        ),
    ]
