# Generated by Django 4.2 on 2025-05-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0002_remove_nation_region_nation_culture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
