# Generated by Django 4.2 on 2025-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0004_nation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
