# Generated by Django 4.2 on 2025-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0005_nation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='nextSlug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Next nation slug'),
        ),
    ]
